### ISSUE TITLE
The visual container of "Box" teams with more than 6 pokemon does not maintain its larger size

### ISSUE THREAD

**Issue by alaserdolphin** [smogon/pokemon-showdown#7736]
![PS Client Box Bug Example](https://user-images.githubusercontent.com/1558717/100480101-4c7b4a80-30be-11eb-86d5-b09206d5266c.png)

On client (untested on web), the visual silver/grey area in the background of each team does not keep its 24-Pokemon size. Creating a new box is fine initially, but the area looks like it does in the photo after the client has been closed and reopened.

This does not seem to be affected by choice of format.

This is on Windows 10; in the odd chance it's related, I also have the issues described within #7699.

**Comment by Zarel** [comment]
This should be fixed by https://github.com/smogon/pokemon-showdown-client/issues/1688

Can you tell me if it isn't?

**Comment by alaserdolphin** [comment]
@Zarel 

This is the bug I was mentioning that is still present

**Comment by Zarel** [comment]
@MacChaeger?
